export const DESKTOP_SERVER_APP_NAME = "@another-workbench/desktop-server";

export const desktopServerDependencies = ["@another-workbench/core", "@another-workbench/adapters", "@another-workbench/shared"];

export * from "./runtime-service.js";
export * from "./remote-auth.js";
export * from "./remote-auth-session-service.js";
export * from "./remote-bootstrap-service.js";
export * from "./remote-connection-service.js";
export * from "./remote-pairing-service.js";
export * from "./remote-protocol.js";
export * from "./remote-server.js";
export * from "./host-relay-client.js";
export * from "./demo-runtime-port.js";
export * from "./demo-service.js";
export * from "./prod-service.js";
export * from "./pi-acp-runtime-port.js";
export * from "./local-preload.js";
export * from "./file-action-service.js";
export * from "./error-log-service.js";
export * from "./diagnostic-log-service.js";
export * from "./host-tools.js";
export * from "./smart-takeover-tool.js";
export * from "./smart-takeover-service.js";
export * from "./takeover-preset-store.js";
export * from "./file-preview-service.js";
export * from "./workspace-file-search-service.js";
export * from "./workspace-registry.js";
export * from "./session-index.js";
export * from "./session-catalog.js";
export * from "./session-discovery.js";
export * from "./session-actions.js";
export * from "./chat-tree-provider.js";
export * from "./workbench-shell-service.js";
export * from "./engine-extensions/codex/turn-changes-store.js";
export * from "./engine-extensions/codex/turn-changes-service.js";
export * from "./engine-control/engine-definition.js";
export * from "./engine-control/engine-registry.js";
export * from "./engine-control/capability-surface.js";
export * from "./engine-control/native-onboarding-contract.js";
